version: '3.8'

services:
  restaurant-api:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MODEL_PATH=/app/app/ai_service/notebooks/models/restaurant_recommender.pkl
      - DATA_PATH=/app/app/ai_service/notebooks/models/restaurant_data.csv
      - SIMILARITY_MATRIX_PATH=/app/app/ai_service/notebooks/models/similarity_matrix.npy
    volumes:
      - ../app/ai_service/notebooks/models:/app/app/ai_service/notebooks/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/public"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - restaurant-api
    restart: unless-stopped
